services:
  api:
    container_name: api-starter
    env_file:
      - ./.env.tests-k6
    ports:
      - 3000:3000
    image: node:${NODE_VERSION}-alpine
    volumes:
      - ./../:/app
    working_dir: /app
    command: sh -c "yarn start"
